Update ksun+susfs.yml

diff --git a/.github/workflows/ksun+susfs.yml b/.github/workflows/ksun+susfs.yml
--- a/.github/workflows/ksun+susfs.yml
+++ b/.github/workflows/ksun+susfs.yml
@@ -81,30 +81,26 @@ jobs:
           
           echo "Applying next SUSFS patches..."
           cp ../../susfs4ksu/kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch ./
-          patch -p1 --forward --fuzz=7 < 10_enable_susfs_for_ksu.patch || echo "Patch failed !"
-             
-          echo "Applying next SUSFS patches..."
-          cp ../../susfs4ksu/kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch ./
-          patch -p1 --forward --fuzz=3 < 10_enable_susfs_for_ksu.patch || true
-
+          patch -p1 --forward --fuzz=7 < 10_enable_susfs_for_ksu.patch || echo "Patch failed !"       
+          
           echo "Applying next SUSFS Fix patches..."
           cp ../../kernel_patches/next/susfs_fix_patches/v1.5.9/fix_apk_sign.c.patch ./
-          patch -p1 --forward --fuzz=3 < fix_apk_sign.c.patch
+          patch -p1 --forward --fuzz=7 < fix_apk_sign.c.patch
               
           cp ../../kernel_patches/next/susfs_fix_patches/v1.5.9/fix_core_hook.c.patch ./
-          patch -p1 --forward --fuzz=3 < fix_core_hook.c.patch
+          patch -p1 --forward --fuzz=7 < fix_core_hook.c.patch
           
           cp ../../kernel_patches/next/susfs_fix_patches/v1.5.9/fix_selinux.c.patch ./
-          patch -p1 --forward --fuzz=3 < fix_selinux.c.patch
+          patch -p1 --forward --fuzz=7 < fix_selinux.c.patch
             
           cp ../../kernel_patches/next/susfs_fix_patches/v1.5.9/fix_ksud.c.patch ./
-          patch -p1 --forward --fuzz=3 < fix_ksud.c.patch
+          patch -p1 --forward --fuzz=7 < fix_ksud.c.patch
 
           cp ../../kernel_patches/next/susfs_fix_patches/v1.5.9/fix_rules.c.patch ./
-          patch -p1 --forward --fuzz=3 < fix_rules.c.patch
+          patch -p1 --forward --fuzz=7 < fix_rules.c.patch
 
           cp ../../kernel_patches/next/susfs_fix_patches/v1.5.9/fix_sucompat.c.patch ./
-          patch -p1 --forward --fuzz=3 < fix_sucompat.c.patch
+          patch -p1 --forward --fuzz=7 < fix_sucompat.c.patch
           
           # Change to common directory and apply SUSFS patch
           cd ..
@@ -116,7 +112,7 @@ jobs:
           cd "$CONFIG"
           # Apply additional patch
           cp ../kernel_patches/next/syscall_hooks.patch ./
-          patch -p1 -F 3 < syscall_hooks.patch
+          patch -p1 -F 7 < syscall_hooks.patch
           
       - name: Apply Hide Stuff Patches
         run: |
@@ -124,7 +120,7 @@ jobs:
           cd "$CONFIG"
           # Apply additional patch
           cp ../kernel_patches/69_hide_stuff.patch ./
-          patch -p1 -F 3 < 69_hide_stuff.patch
+          patch -p1 -F 7 < 69_hide_stuff.patch
 
       - name: Add SUSFS Configuration Settings
         run: |
